### ISSUE TITLE
a list of wktStrings of interest

### ISSUE THREAD

**Issue by jhpoelen** [diatomsRcool/checklists#1]
if you make a tsv file with all wktStrings of interest, something like

 country code | wktString 
 --- | --- 
 something | something

then, I can make a little script to request all wktStrings and run it in jenkins every 10 mins. 

idea?

**Comment by jhpoelen** [comment]
this scripts would keep feeding the cluster with requests without overwhelming it:

for all wktString
  request api.effechecka.org/checklist?wktString=[...]

then after all are done, you can download all by saying

for all countryCode, wktString
  download api.effechecka.org/checklist.tsv?wktString=[something] > checklist/[countryCode].tsv

**Comment by diatomsRcool** [comment]
ok, I will make the wkString file

**Comment by diatomsRcool** [comment]
File added

**Comment by jhpoelen** [comment]
Thanks! 

I've just created http://archive.guoda.bio/view/Effechecka%20Jobs/job/Checklists/ that runs script [wkt_string.sh](../blob/master/wkt_string.sh) every 10 minutes. You know you when the checklists are  done when the workspace of the jenkins job is filled with tsv files with checklists in it. Note that only the first line in the checklist is printed. Once all the checklists have been calculated you can easy change  the script to download all the items.

@jhammock is running a pretty hefty job right now, so it might be a while, but at least . . . the hamsters are busy while you sleep.

**Comment by diatomsRcool** [comment]
Great! Sounds like I need to learn Jenkins. I checked it out a while back, but it seemed to be designed for doing automatic push to github. I wasn't sure how to set it up to do other things.

**Comment by diatomsRcool** [comment]
Is there an indicator for knowing when the Jenkins job is finished?

**Comment by jhpoelen** [comment]
previously, you'd have to inspect the tsv file related to the geonames ids. Now, I've created a little script that lists the status of the checklist in a single file:

http://archive.guoda.bio/job/Checklists/ws/checklist_status.tsv

in workspace http://archive.guoda.bio/job/Checklists/ws

the status codes are http status code. A quick glance tells me checklists have been calculated (status=200) or generated bad requests (code=400) or are too long (code=414).

**Comment by jhpoelen** [comment]
The ones that are pending, should have code=503 , and I don't see this status code.

**Comment by jhpoelen** [comment]
So, with this, I think all checklists with valid wkt strings have been calculated. You might want to double check the wkt strings associated with the 4xx codes and double check format / length.

**Comment by diatomsRcool** [comment]
OK. That makes sense. I was looking through the full files and saw that some had nothing while others had a message saying the URL was too long. I'll see what the problem is.

**Comment by diatomsRcool** [comment]
I think I fixed the wkstring.tsv file. I don't see any code to regenerate the .sh file, tho.

**Comment by jhpoelen** [comment]
great! changes are automatically included as checklist_status_gen.sh uses your updated list to generate a checklist_status.sh script with all the appropriate commands in it. wkt_string.sh is not longer used.

Looks like only 4043988 is returning status 400. please confirm.

**Comment by diatomsRcool** [comment]
confirmed and fixed

**Comment by jhpoelen** [comment]
nice! I did found a little bug, preventing the "in progress/busy checklists" from being shown. Implemented fix. After fix, a bunch of 503s showed up, so cluster is still dutifully crunching on the checklists.

**Comment by jhpoelen** [comment]
A quick glance at the cluster tells me that checklist is only able to use about 25% of capacity, because there's a bunch of folks running pyspark-shells. Perhaps @jhammock @mjcollin or @godfoder can tell you how to cleanup inactive pyspark-shells that are left running by unsuspecting guoda newbies.

![screenshot from 2017-11-13 14-03-19](https://user-images.githubusercontent.com/1084872/32751848-fa15e1cc-c87b-11e7-8f2b-103318c277ff.png)

**Comment by jhammock** [comment]
I just nuked 3 servers from at least 4 days ago, but it looks like a lot of people are active today. Still, might be worth trying again now.

**Comment by jhpoelen** [comment]
Thanks @jhammock . Note that the travis job at http://archive.guoda.bio/job/Checklists pokes the cluster every 10 minutes, triggering new checklist calculations when needed, so no need to do any manual prodding.

**Comment by jhpoelen** [comment]
@diatomsRcool please have a look at the recently generated http://archive.guoda.bio/job/Checklists/ws/checklist.tar.gz . This should contains all the checklists you were interested in + associated scripts and wkt lists. This archive can be regenerated / changed when needed. Jenkins in configured to trigger re-harvest of checklists on change in this github repo (i.e., https://github.com/diatomsRcool/checklists). Please close this issue when results are as expected. Otherwise, please comment.

**Comment by diatomsRcool** [comment]
Awesome! Thanks. I need to sit down with you and find out how to use Jenkins.

**Comment by jhpoelen** [comment]
Ok. Happy to spent some time on sharing Jenkins recipes. . . perhaps something to discuss for the next GUODA meeting. I think that @mjcollin @godfoder are planning the next one.
