### ISSUE TITLE
suspected invalid wktString for geonames id 2309096	

### ISSUE THREAD

**Issue by jhpoelen** [diatomsRcool/checklists#2]
From http://archive.guoda.bio/job/Checklists/ws/checklist_status.tsv/*view*/ 

```
[...]
2300660	2017-11-15T12:11:14-05:00	 200
2309096	2017-11-15T12:11:14-05:00	 400
2328926	2017-11-15T12:11:14-05:00	 503
[...]
```

**Comment by diatomsRcool** [comment]
Yeah, I know. I have no idea what the problem is. It shows up in the 
effechecka map just fine.

**Comment by jhpoelen** [comment]
The issue was inconsistent decimal usage in wkt string, see https://github.com/diatomsRcool/checklists/commit/d34b6d08f95d08dae979fa568953ae2db748c320 for fix.

**Comment by jhpoelen** [comment]
From  http://archive.guoda.bio/job/Checklists/ws/checklist_status.tsv/*view*/ after fix - 

```
[...]
2300660	2017-11-15T18:26:04-05:00	 200
2309096	2017-11-15T18:26:04-05:00	 503
2328926	2017-11-15T18:26:04-05:00	 503
[...]
```
