### ISSUE TITLE
updating checklists

### ISSUE THREAD

**Issue by diatomsRcool** [diatomsRcool/checklists#3]
I added two new wkt strings to the file this morning and Jenkins ran twice, but stopped. Isn't it supposed to keep going?

**Comment by jhpoelen** [comment]
Previously, the status update script ran every 10 mins. Currently, the status update *and* checklist download script runs each time a change is detected in the github repository. If you'd like to poke around and configure this to suit your needs, or trigger the job manually, I'd suggest to have a look as the jenkins job and associated script [checklist_script_gen.sh](../blob/master/checklist_script_gen.sh). 

Also, as far as I can tell, one wkt string was added with id 1279685 , which was calculated a couple of days ago.
